begin;
set local role service_role;
do $$
declare u bigint:=910000000000001; v bigint:=910000000000002; a uuid; i uuid; r jsonb; n integer; blocked boolean;
begin
 insert into public.pr_users(chat_id) values(u),(v);
 insert into public.pr_accounts(user_id,name,positions) values(u,'QA','[{"key":"cg:bitcoin","name":"Bitcoin","quantity":"1","verified":true},{"key":"moex:SBER","name":"Сбер","quantity":"20","verified":true}]') returning id into a;
 insert into public.pr_imports(user_id,account_id,base_version,status,rows) values(u,a,0,'preview','[{"key":"cg:bitcoin","name":"Bitcoin","quantity":"0.123456789012345678","verified":true}]') returning id into i;
 blocked:=false;
 begin perform public.pr_commit(i,v); exception when others then blocked:=sqlerrm='import_not_found'; end;
 if not blocked then raise exception 'QA owner isolation failed';end if;
 r:=public.pr_commit(i,u);
 select jsonb_array_length(positions) into n from public.pr_accounts where id=a;
 if n<>2 then raise exception 'QA partial erased unseen position';end if;
 if not exists(select 1 from public.pr_accounts a2, jsonb_array_elements(a2.positions) as qa_pos(value) where a2.id=a and qa_pos.value->>'key'='cg:bitcoin' and qa_pos.value->>'quantity'='0.123456789012345678') then raise exception 'QA decimal precision lost';end if;
 r:=public.pr_commit(i,u);
 if not (r->>'already_committed')::boolean then raise exception 'QA duplicate confirmation';end if;
 if (select version from public.pr_accounts where id=a)<>1 then raise exception 'QA duplicate version increment';end if;
 insert into public.pr_imports(user_id,account_id,base_version,status,rows) values(u,a,0,'preview','[{"key":"cg:bitcoin","name":"Bitcoin","quantity":"10","verified":true}]') returning id into i;
 blocked:=false;
 begin perform public.pr_commit(i,u);exception when others then blocked:=sqlerrm='stale_import';end;
 if not blocked then raise exception 'QA stale import overwrote newer portfolio';end if;
 update public.pr_imports set status='cancelled' where id=i;
 insert into public.pr_imports(user_id,account_id,base_version,status,mode,rows) values(u,a,1,'preview','replace','[{"key":"moex:SBER","name":"Сбер","quantity":"3","verified":true}]') returning id into i;
 perform public.pr_commit(i,u);
 if (select jsonb_array_length(positions) from public.pr_accounts where id=a)<>1 then raise exception 'QA replacement failed';end if;
 insert into public.pr_imports(user_id,account_id,base_version,status,rows) values(u,a,2,'preview','[{"key":"moex:SBER","name":"Сбер","quantity":"0","verified":true}]') returning id into i;
 perform public.pr_commit(i,u);
 if (select jsonb_array_length(positions) from public.pr_accounts where id=a)<>0 then raise exception 'QA zero did not remove';end if;
 insert into public.pr_imports(user_id,account_id,base_version,status,rows) values(u,a,3,'preview','[{"key":"mystery","name":"Mystery","quantity":null,"verified":false}]') returning id into i;
 blocked:=false;
 begin perform public.pr_commit(i,u);exception when others then blocked:=sqlerrm='unresolved_rows';end;
 if not blocked then raise exception 'QA unresolved asset committed';end if;
 perform public.pr_enqueue('qa-dedup','digest',jsonb_build_object('chat_id',u),u);
 perform public.pr_enqueue('qa-dedup','digest',jsonb_build_object('chat_id',u),u);
 if (select count(*) from public.pr_jobs where job_key='qa-dedup')<>1 then raise exception 'QA duplicate job';end if;
 perform public.pr_forget(u);
 if exists(select 1 from public.pr_accounts where user_id=u) or exists(select 1 from public.pr_history where account_id=a) or exists(select 1 from public.pr_jobs where user_id=u) then raise exception 'QA delete did not cascade';end if;
end $$;
reset role;
select 'PASS: owner isolation, partial update, exact decimal, idempotent commit, stale version protection, replacement, zero removal, unresolved assets, job deduplication, deletion' as result;
rollback;
